In [93]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re
import ast

In [ ]:
#The Dataframes

In [29]:
appstore_data_temp1 = pd.read_csv("dataset/appstore_apps_by_name_1.csv")
appstore_data_temp2 = pd.read_csv("dataset/appstore_apps_by_name_2.csv")
appstore_data_temp3 = pd.read_csv("dataset/appstore_apps_by_name_3.csv")
appstore_data_temp4 = pd.read_csv("dataset/appstore_apps_by_name_4.csv")
playstore_data = pd.read_csv("dataset/cleaned_googleplaystore.csv")

In [ ]:
#CHecking if the app names in the app store dataset are same as the play store dataset

In [30]:
appstore_app_names_temp1 = appstore_data_temp1["App"].dropna().unique().tolist()
appstore_app_names_temp2 = appstore_data_temp2["App"].dropna().unique().tolist()
appstore_app_names_temp3 = appstore_data_temp3["App"].dropna().unique().tolist()
appstore_app_names_temp4 = appstore_data_temp4["App"].dropna().unique().tolist()
playstore_app_names = playstore_data["App"].dropna().unique().tolist()

In [33]:
def check_app_names(temp):
    count = 0
    for i in temp:
        if i in playstore_app_names:
            count += 1
    print(len(temp), count)

In [34]:
check_app_names(appstore_app_names_temp1)
check_app_names(appstore_app_names_temp2)
check_app_names(appstore_app_names_temp3)
check_app_names(appstore_app_names_temp4)

500 500
568 568
499 499
565 565

In [ ]:
#Combining the Dataframes of the appstore datasets

In [35]:
appstore_data = pd.concat([appstore_data_temp1, appstore_data_temp2, appstore_data_temp3, appstore_data_temp4], ignore_index=True)

In [37]:
appstore_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2132 entries, 0 to 2131
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   App                         2132 non-null   object
 1   as_app_id                   2132 non-null   int64
 2   as_title                    2132 non-null   object
 3   as_store                    2132 non-null   object
 4   as_genres                   2132 non-null   object
 5   as_primary_genre            2132 non-null   object
 6   as_content_rating           2132 non-null   object
 7   as_size                     2132 non-null   int64
 8   as_required_os_version      2132 non-null   object
 9   as_released                 2132 non-null   object
 10  as_updated                  2132 non-null   object
 11  as_version                  2132 non-null   object
 12  as_price                    2132 non-null   float64
 13  as_free                     2132 non-null   bool
 14  as_score                    2132 non-null   float64
 15  as_reviews                  2132 non-null   int64
 16  as_current_version_score    2132 non-null   float64
 17  as_current_version_reviews  2132 non-null   int64
dtypes: bool(1), float64(3), int64(4), object(10)
memory usage: 285.4+ KB

In [ ]:
#Dropping unncessary fields of the appstore data

In [40]:
appstore_data = appstore_data.drop(columns=["as_title", "as_released", "as_updated", "as_current_version_score", "as_current_version_reviews"], axis = 1)

In [42]:
appstore_data = appstore_data.drop(columns=["as_app_id"], axis = 1)

In [160]:
appstore_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2132 entries, 0 to 2131
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   App                     2132 non-null   object
 1   as_store                2132 non-null   object
 2   as_genres               2132 non-null   object
 3   as_primary_genre        2132 non-null   object
 4   as_content_rating       2132 non-null   object
 5   as_size                 2132 non-null   int64
 6   as_required_os_version  2132 non-null   object
 7   as_version              2132 non-null   object
 8   as_price                2132 non-null   float64
 9   as_free                 2132 non-null   bool
 10  as_score                2132 non-null   float64
 11  as_reviews              2132 non-null   float64
dtypes: bool(1), float64(3), int64(1), object(7)
memory usage: 185.4+ KB

In [56]:
#checking null values

In [57]:
print(playstore_data.isnull().sum())

App               0
Category          0
Rating            0
Reviews           0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Size_MB           0
and_ver_min       0
curr_ver_min      0
dtype: int64

In [58]:
print(appstore_data.isnull().sum())

App                       0
as_store                  0
as_genres                 0
as_primary_genre          0
as_content_rating         0
as_size                   0
as_required_os_version    0
as_version                0
as_price                  0
as_free                   0
as_score                  0
as_reviews                0
dtype: int64

In [59]:
#Stroe values in appstore data

In [60]:
appstore_data["as_store"].value_counts()

as_store
apple    2132
Name: count, dtype: int64

In [ ]:
#standardizing genres of the appstore dataset

In [120]:
appstore_data["as_genres"].value_counts()

as_genres
[Medical, Health & Fitness]       86
[Shopping, Lifestyle]             74
[Social Networking, Lifestyle]    71
[Health & Fitness, Lifestyle]     69
[Lifestyle, Social Networking]    47
                                  ..
[Lifestyle, Music]                 1
[Games, Board, Card]               1
[Entertainment, Games, Family]     1
[Games, Puzzle, Action]            1
[Sports, Health & Fitness]         1
Name: count, Length: 436, dtype: int64

In [68]:
def rating_change(x):
    if isinstance(x, str):
        x = x.strip()
        return x.split(", ")
    return np.nan

In [69]:
appstore_data["as_genres"] = appstore_data["as_genres"].apply(rating_change)

In [ ]:
#standardizing category of the appstore dataset

In [133]:
appstore_data["as_primary_genre"].value_counts()

as_primary_genre
Games                     354
Education                 186
Health & Fitness          179
Social Networking         175
Lifestyle                 175
Medical                   172
Entertainment             154
Finance                   118
Utilities                  96
Shopping                   86
Business                   86
Food & Drink               77
Productivity               60
Photo & Video              54
Book                       43
Reference                  23
Music                      20
Graphics & Design          20
Travel                     18
Navigation                 13
News                       10
Sports                      9
Magazines & Newspapers      2
Developer Tools             1
Weather                     1
Name: count, dtype: int64

In [ ]:
#checking content ratings of appstore dataset

In [146]:
appstore_data["as_content_rating"].value_counts()

as_content_rating
4+     1182
12+     470
17+     398
9+       82
Name: count, dtype: int64

In [ ]:
#changing dtype of reviews column

In [159]:
appstore_data["as_reviews"] = appstore_data["as_reviews"].astype(float)

In [22]:
appstore_data.head()

,App,as_app_id,as_title,as_store,as_genres,as_primary_genre,as_content_rating,as_size,as_required_os_version,as_released,as_updated,as_version,as_price,as_free,as_score,as_reviews,as_current_version_score,as_current_version_reviews
0,Photo Editor & Candy Camera & Grid & ScrapBook,597851882,Photo Editor,apple,"Photo & Video, Graphics & Design",Photo & Video,12+,224247808,15.0,2013-03-04T23:48:46Z,2025-05-05T16:58:11Z,5.5.7,0.0,True,4.61130,43072,4.61130,43072
1,Coloring book moana,1400326821,Disney Coloring World,apple,"Entertainment, Education",Entertainment,4+,1298546688,13.0,2018-12-20T08:52:32Z,2025-08-28T09:01:46Z,17.2.0,0.0,True,4.38417,204845,4.38417,204845
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",6447543971,Cool Themes & Fonts: Cute Text,apple,"Graphics & Design, Entertainment",Graphics & Design,4+,162102272,15.0,2023-05-18T07:00:00Z,2025-09-19T02:15:03Z,1.9.8,0.0,True,4.64858,30573,4.64858,30573
3,Sketch - Draw & Paint,506003812,"Paper: Sketch, Draw & Create",apple,"Productivity, Graphics & Design",Productivity,4+,175809536,13.0,2012-03-29T07:00:00Z,2025-07-22T18:59:39Z,5.5.9,0.0,True,4.57904,68151,4.57904,68151
4,Pixel Draw - Number Art Coloring Book,1315399681,Pixelmania - Number Coloring,apple,"Entertainment, Puzzle, Family, Games",Entertainment,4+,54242304,12.0,2017-11-22T17:24:19Z,2023-12-26T04:37:20Z,3.3.0,0.0,True,4.47975,4346,4.47975,4346

In [45]:
#Dropping unncessary columns in playstore dataset

In [46]:
playstore_data = playstore_data.drop(columns=["curr_ver", "and_ver"], axis = 1)

In [47]:
playstore_data.head()

,App,Category,Rating,Reviews,Installs,Type,Price,Content Rating,Genres,Last Updated,Size_MB,and_ver_min,curr_ver_min
0,Photo Editor & Candy Camera & Grid & ScrapBook,"['ART', 'DESIGN']",4.1,159.0,10000.0,Free,0.0,Everyone,['Art & Design'],2018-01-07,19.0,4.0,1.0
1,Coloring book moana,"['ART', 'DESIGN']",3.9,967.0,500000.0,Free,0.0,Everyone,"['Art & Design', 'Pretend Play']",2018-01-15,14.0,4.0,2.0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...","['ART', 'DESIGN']",4.7,87510.0,5000000.0,Free,0.0,Everyone,['Art & Design'],2018-08-01,8.7,4.0,1.2
3,Sketch - Draw & Paint,"['ART', 'DESIGN']",4.5,215644.0,50000000.0,Free,0.0,Teen,['Art & Design'],2018-06-08,25.0,4.2,2.0
4,Pixel Draw - Number Art Coloring Book,"['ART', 'DESIGN']",4.3,967.0,100000.0,Free,0.0,Everyone,"['Art & Design', 'Creativity']",2018-06-20,2.8,4.4,1.1

In [48]:
#Standardizing Content Rating in playstore data

In [49]:
playstore_data["Content Rating"].value_counts()

Content Rating
Everyone           8714
Teen               1208
Mature 17+          499
Everyone 10+        413
Adults only 18+       3
Unrated               2
Name: count, dtype: int64

In [50]:
def stand_cont_rat(x):
    if isinstance(x, str):
        x = x.strip()
        if x == "Mature 17+":
            return "Mature"
        elif x == "Everyone 10+":
            return "Teen"
        elif x == "Adults only 18+":
            return "Adults"
        else:
            return x
    return np.nan

In [51]:
playstore_data["Content Rating"] = playstore_data["Content Rating"].apply(stand_cont_rat)

In [52]:
playstore_data["Content Rating"].value_counts()

Content Rating
Everyone    8714
Teen        1621
Mature       499
Adults         3
Unrated        2
Name: count, dtype: int64

In [53]:
#Last Updated Column of Playstore Dataset

In [54]:
"""Since the playstore dataset is very old and the appstore one is relatively upto date, the "Last Updated" values for the playstore data 
   are in 2018. Since there is no latest data for them, and considering we need a balance in that, we are going to avoid the appstore 
   "Last Updated" values. Consider only the playstore's value for the same."""

'Since the playstore dataset is very old and the appstore one is relatively upto date, the "Last Updated" values for the playstore data \n   are in 2018. Since there is no latest data for them, and considering we need a balance in that, we are going to avoid the appstore \n   "Last Updated" values. Consider only the playstore\'s value for the same.'

In [157]:
#Size Column of Playstore Dataset

In [158]:
"""Just like the Last Updated Updated field, Size also chnages through years. So im using the playstore data's Size just as it is."""

"Just like the Last Updated Updated field, Size also chnages through years. So im using the playstore data's Size just as it is."

In [ ]:
#Adding store column to the dataset

In [61]:
appstore_app_names = appstore_data["App"].dropna().unique().tolist()

print(len(appstore_app_names))

2132

In [72]:
playstore_data["Store"] = "[android]"

In [73]:
for app in playstore_data["App"]:
    if app.strip() in appstore_app_names:
        playstore_data.loc[playstore_data["App"] == app, "Store"] = "[android, apple]"

In [74]:
playstore_data["Store"].value_counts()

Store
[android]           7835
[android, apple]    3004
Name: count, dtype: int64

In [99]:
#merging genre names in the datasets

In [100]:
playstore_data["new_gen"] = "Yes"

In [116]:
app_genres_dict = {}
for idx, row in appstore_data.iterrows():
    app_genres_dict[row["App"]] = ast.literal_eval(str(row["as_genres"]))

play_genres_dict = {}
for idx, row in playstore_data.iterrows():
    play_genres_dict[row["App"]] = ast.literal_eval(str(row["Genres"]))

In [125]:
for app in appstore_app_names:
    for i in app_genres_dict[app]:
        if i not in play_genres_dict[app]:
            play_genres_dict[app].append(i)

In [126]:
play_genres_dict

{'Photo Editor & Candy Camera & Grid & ScrapBook': ['Art & Design',
  'Photo & Video',
  'Graphics & Design'],
 'Coloring book moana': ['Art & Design',
  'Pretend Play',
  'Entertainment',
  'Education'],
 'U Launcher Lite – FREE Live Cool Themes, Hide Apps': ['Art & Design',
  'Graphics & Design',
  'Entertainment'],
 'Sketch - Draw & Paint': ['Art & Design',
  'Productivity',
  'Graphics & Design'],
 'Pixel Draw - Number Art Coloring Book': ['Art & Design',
  'Creativity',
  'Entertainment',
  'Puzzle',
  'Family',
  'Games'],
 'Paper flowers instructions': ['Art & Design',
  'Entertainment',
  'Family',
  'Trivia',
  'Games'],
 'Smoke Effect Photo Maker - Smoke Editor': ['Art & Design',
  'Photo & Video',
  'Entertainment'],
 'Infinite Painter': ['Art & Design', 'Graphics & Design', 'Productivity'],
 'Garden Coloring Book': ['Art & Design',
  'Games',
  'Entertainment',
  'Puzzle',
  'Board'],
 'Kids Paint Free - Drawing Fun': ['Art & Design',
  'Creativity',
  'Education',
  'Entertainment'],
 'Text on Photo - Fonteee': ['Art & Design', 'Photo & Video'],
 'Name Art Photo Editor - Focus n Filters': ['Art & Design',
  'Photo & Video',
  'Graphics & Design'],
 'Tattoo Name On My Photo Editor': ['Art & Design',
  'Lifestyle',
  'Photo & Video'],
 'Mandala Coloring Book': ['Art & Design',
  'Games',
  'Casual',
  'Entertainment',
  'Board'],
 '3D Color Pixel by Number - Sandbox Art Coloring': ['Art & Design',
  'Entertainment',
  'Games',
  'Family',
  'Puzzle'],
 'Learn To Draw Kawaii Characters': ['Art & Design',
  'Entertainment',
  'Education'],
 'Photo Designer - Write your name with shapes': ['Art & Design',
  'Photo & Video',
  'Shopping'],
 '350 Diy Room Decor Ideas': ['Art & Design',
  'Games',
  'Graphics & Design',
  'Casual',
  'Simulation'],
 'FlipaClip - Cartoon animation': ['Art & Design',
  'Graphics & Design',
  'Productivity'],
 'ibis Paint X': ['Art & Design', 'Graphics & Design', 'Entertainment'],
 'Logo Maker - Small Business': ['Art & Design',
  'Graphics & Design',
  'Business'],
 "Boys Photo Editor - Six Pack & Men's Suit": ['Art & Design',
  'Photo & Video',
  'Social Networking'],
 'Superheroes Wallpapers | 4K Backgrounds': ['Art & Design',
  'Entertainment',
  'Photo & Video'],
 'Mcqueen Coloring pages': ['Art & Design',
  'Action & Adventure',
  'Entertainment'],
 'HD Mickey Minnie Wallpapers': ['Art & Design', 'Lifestyle', 'Utilities'],
 'Harley Quinn wallpapers HD': ['Art & Design', 'Lifestyle', 'Entertainment'],
 'Colorfit - Drawing & Coloring': ['Art & Design',
  'Creativity',
  'Lifestyle',
  'Entertainment'],
 'Animated Photo Editor': ['Art & Design', 'Photo & Video', 'Entertainment'],
 'Pencil Sketch Drawing': ['Art & Design', 'Photo & Video', 'Entertainment'],
 'Easy Realistic Drawing Tutorial': ['Art & Design',
  'Education',
  'Entertainment'],
 'Pink Silver Bow Keyboard Theme': ['Art & Design',
  'Utilities',
  'Entertainment'],
 'Art Drawing Ideas': ['Art & Design', 'Productivity', 'Photo & Video'],
 'Anime Manga Coloring Book': ['Art & Design',
  'Entertainment',
  'Puzzle',
  'Games',
  'Trivia'],
 'Easy Origami Ideas': ['Art & Design', 'Entertainment', 'Education'],
 'I Creative Idea': ['Art & Design', 'Productivity', 'Education'],
 'How to draw Ladybug and Cat Noir': ['Art & Design',
  'Games',
  'Racing',
  'Family',
  'Entertainment'],
 'UNICORN - Color By Number & Pixel Art Coloring': ['Art & Design',
  'Creativity',
  'Entertainment',
  'Lifestyle'],
 'Floor Plan Creator': ['Art & Design', 'Productivity', 'Business'],
 'PIP Camera - PIP Collage Maker': ['Art & Design',
  'Photo & Video',
  'Productivity'],
 'How To Color Disney Princess - Coloring Pages': ['Art & Design',
  'Entertainment',
  'Education'],
 'Drawing Clothes Fashion Ideas': ['Art & Design',
  'Graphics & Design',
  'Productivity'],
 'Sad Poetry Photo Frames 2018': ['Art & Design',
  'Photo & Video',
  'Graphics & Design'],
 'Textgram - write on photos': ['Art & Design',
  'Photo & Video',
  'Entertainment'],
 'Paint Splash!': ['Art & Design',
  'Creativity',
  'Games',
  'Entertainment',
  'Music',
  'Word'],
 'Popsicle Sticks and Similar DIY Craft Ideas': ['Art & Design',
  'Shopping',
  'Lifestyle'],
 'Canva: Poster, banner, card maker & graphic design': ['Art & Design',
  'Photo & Video',
  'Productivity'],
 'Install images with music to make video without Net - 2018': ['Art & Design',
  'Photo & Video',
  'Utilities'],
 'Little Teddy Bear Colouring Book Game': ['Art & Design',
  'Games',
  'Entertainment',
  'Simulation',
  'Puzzle'],
 'How To Draw Food': ['Art & Design', 'Entertainment', 'Education'],
 'Monster Truck Stunt 3D 2019': ['Auto & Vehicles',
  'Games',
  'Strategy',
  'Entertainment',
  'Racing'],
 'Real Tractor Farming': ['Auto & Vehicles', 'Games', 'Simulation'],
 'Ultimate F1 Racing Championship': ['Auto & Vehicles',
  'Games',
  'Action',
  'Racing',
  'Entertainment'],
 'Used Cars and Trucks for Sale': ['Auto & Vehicles', 'Shopping', 'Lifestyle'],
 'American Muscle Car Race': ['Auto & Vehicles', 'Entertainment', 'Sports'],
 'Offroad Oil Tanker Driver Transport Truck 2019': ['Auto & Vehicles',
  'Navigation',
  'Weather'],
 'Tickets SDA 2018 and Exam from the State Traffic Safety Inspectorate with Drom.ru': ['Auto & Vehicles',
  'Productivity',
  'Utilities'],
 'Gas Prices (Germany only)': ['Auto & Vehicles', 'Travel', 'Navigation'],
 'Extreme Rally Championship': ['Auto & Vehicles',
  'Games',
  'Simulation',
  'Racing',
  'Sports'],
 'Restart Navigator': ['Auto & Vehicles', 'Travel', 'Lifestyle'],
 'REG - Check the regnumber, find information about Swedish vehicles': ['Auto & Vehicles',
  'Shopping',
  'Reference'],
 'CityBus Lviv': ['Auto & Vehicles', 'Travel', 'Navigation'],
 'CDL Practice Test 2018 Edition': ['Auto & Vehicles',
  'Education',
  'Utilities'],
 'ezETC (ETC balance inquiry, meter trial, real-time traffic)': ['Auto & Vehicles',
  'Travel',
  'Navigation'],
 'Free VIN Report for Used Cars': ['Auto & Vehicles', 'Shopping', 'Lifestyle'],
 'DMV Permit Practice Test 2018 Edition': ['Auto & Vehicles',
  'Education',
  'Reference'],
 'Check Vehicle Tax': ['Auto & Vehicles', 'Finance', 'Productivity'],
 'Used Cars Mexico': ['Auto & Vehicles', 'Shopping', 'Lifestyle'],
 'Ulysse Speedometer': ['Auto & Vehicles', 'Utilities', 'Travel'],
 'REPUVE': ['Auto & Vehicles', 'Reference', 'Finance'],
 'Used cars for sale - Trovit': ['Auto & Vehicles', 'Shopping', 'Lifestyle'],
 'Fines of the State Traffic Safety Inspectorate are official: inspection, payment of fines': ['Auto & Vehicles',
  'Finance',
  'Utilities'],
 'SK Enca Direct Malls - Used Cars Search': ['Auto & Vehicles',
  'Shopping',
  'Lifestyle'],
 'Android Auto - Maps, Media, Messaging & Voice': ['Auto & Vehicles',
  'Navigation',
  'Travel'],
 'PDD-UA': ['Auto & Vehicles', 'Lifestyle', 'Business'],
 'Tickets SDA 2019 + Exam RF': ['Auto & Vehicles', 'Medical', 'Education'],
 'Super Cars Wallpapers And Backgrounds': ['Auto & Vehicles',
  'Lifestyle',
  'Utilities'],
 'Police Lights, Sirens & Follow Me': ['Auto & Vehicles',
  'Entertainment',
  'Utilities'],
 'Police Detector (Speed Camera Radar)': ['Auto & Vehicles',
  'Navigation',
  'Travel'],
 'Best Car Wallpapers': ['Auto & Vehicles', 'Photo & Video', 'Lifestyle'],
 'Tickets + PDA 2018 Exam': ['Auto & Vehicles', 'Education', 'Reference'],
 'Pick Your Part Garage': ['Auto & Vehicles', 'Shopping'],
 'PakWheels: Buy & Sell Cars': ['Auto & Vehicles', 'Lifestyle', 'Utilities'],
 'Supervision service': ['Auto & Vehicles', 'Business', 'Productivity'],
 'Speed Camera Detector - Traffic & Speed Alert': ['Auto & Vehicles',
  'Navigation',
  'Travel'],
 'Used car search Goo net whole car Go to net': ['Auto & Vehicles',
  'Shopping',
  'Lifestyle'],
 'CarMax – Cars for Sale: Search Used Car Inventory': ['Auto & Vehicles',
  'Lifestyle',
  'Shopping'],
 'BEST CAR SOUNDS': ['Auto & Vehicles', 'Entertainment', 'Lifestyle'],
 'RST - Sale of cars on the PCT': ['Auto & Vehicles', 'Shopping', 'Lifestyle'],
 'AutoScout24 Switzerland – Find your new car': ['Auto & Vehicles',
  'Productivity',
  'Lifestyle'],
 'Zona Azul Digital Fácil SP CET - OFFICIAL São Paulo': ['Auto & Vehicles',
  'Travel',
  'Navigation'],
 'SMS Park': ['Auto & Vehicles', 'Travel', 'Navigation'],
 'SKencar': ['Auto & Vehicles',
  'Games',
  'Simulation',
  'Entertainment',
  'Casual'],
 'Fuelio: Gas log & costs': ['Auto & Vehicles', 'Travel', 'Navigation'],
 'auto fines': ['Auto & Vehicles', 'Productivity', 'Utilities'],
 'Used car is the first car - used car purchase, used car quotation, dealer information to': ['Auto & Vehicles',
  'Shopping',
  'Lifestyle'],
 'All of the parking lot - National Park application (parking lot search / parking sharing / discount payment)': ['Auto & Vehicles',
  'Navigation',
  'Travel'],
 'Inquiry Fines and Debits of Vehicles': ['Auto & Vehicles',
  'Business',
  'Finance'],
 'Gas Station': ['Auto & Vehicles', 'Travel', 'Navigation'],
 'Hush - Beauty for Everyone': ['Beauty',
  'Photo & Video',
  'Graphics & Design'],
 'ipsy: Makeup, Beauty, and Tips': ['Beauty', 'Shopping', 'Lifestyle'],
 'Natural recipes for your beauty': ['Beauty',
  'Food & Drink',
  'Health & Fitness'],
 'BestCam Selfie-selfie, beauty camera, photo editor': ['Beauty',
  'Photo & Video',
  'Social Networking'],
 'Mirror - Zoom & Exposure -': ['Beauty', 'Lifestyle', 'Health & Fitness'],
 'Beauty Selfie Camera': ['Beauty', 'Photo & Video', 'Entertainment'],
 'Hairstyles step by step': ['Beauty', 'Lifestyle', 'Entertainment'],
 'Filters for Selfie': ['Beauty', 'Photo & Video'],
 'Tie - Always be happy': ['Beauty', 'Graphics & Design', 'Music'],
 'Ulta Beauty': ['Beauty', 'Shopping', 'Lifestyle'],
 'Prom MakeUp Tutorial': ['Beauty', 'Graphics & Design', 'Lifestyle'],
 'Selfie Camera': ['Beauty', 'Photo & Video', 'Lifestyle'],
 'Sweet Selfie Beauty Camera': ['Beauty', 'Photo & Video', 'Entertainment'],
 'Colors of white in Urdu': ['Beauty', 'Reference', 'Entertainment'],
 'Selfie Camera Photo Editor & Filter & Sticker': ['Beauty',
  'Photo & Video',
  'Entertainment'],
 'Wrinkles and rejuvenation': ['Beauty', 'Health & Fitness', 'Lifestyle'],
 'Eyes Makeup Beauty Tips': ['Beauty', 'Graphics & Design', 'Lifestyle'],
 'Photo Editor 2018': ['Beauty', 'Graphics & Design', 'Photo & Video'],
 'Step By Step Eyes Makeup Tutorial': ['Beauty',
  'Graphics & Design',
  'Lifestyle'],
 'Beauty Camera - Selfie Camera': ['Beauty', 'Photo & Video', 'Lifestyle'],
 'Girls Hairstyles': ['Beauty', 'Lifestyle', 'Entertainment'],
 'Mirror Camera (Mirror + Selfie Camera)': ['Beauty',
  'Lifestyle',
  'Health & Fitness'],
 'Beauty Tips - Beauty Tips in Sinhala': ['Beauty', 'Shopping', 'Lifestyle'],
 'Haircut Tutorials/Haircut Videos': ['Beauty', 'Games', 'Family', 'Casual'],
 'Sephora: Skin Care, Beauty Makeup & Fragrance Shop': ['Beauty',
  'Shopping',
  'Lifestyle'],
 'Manicure - nail design': ['Beauty', 'Lifestyle', 'Entertainment'],
 'Sticker Camera - Selfie Filters, Beauty Camera': ['Beauty',
  'Photo & Video',
  'Entertainment'],
 'Filters for B Live': ['Beauty', 'Photo & Video', 'Entertainment'],
 'Skin Care and Natural Beauty': ['Beauty', 'Shopping', 'Lifestyle'],
 'Facial Wrinkle Reduction': ['Beauty', 'Health & Fitness', 'Reference'],
 'Makeup Videos': ['Beauty', 'Photo & Video', 'Lifestyle'],
 'Secrets of beauty, youth and health': ['Beauty',
  'Shopping',
  'Health & Fitness'],
 'Recipes and tips for losing weight': ['Beauty',
  'Food & Drink',
  'Health & Fitness'],
 'Discover Color': ['Beauty', 'Lifestyle', 'Shopping'],
 'Eyeliner step by step 2018': ['Beauty', 'Graphics & Design', 'Lifestyle'],
 'Dresses Ideas & Fashions +3000': ['Beauty', 'Shopping', 'Lifestyle'],
 'Lady adviser (beauty, health)': ['Beauty', 'Lifestyle', 'Health & Fitness'],
 'Step By Step Hairstyles For Women': ['Beauty', 'Lifestyle', 'Entertainment'],
 'Rainbow Camera': ['Beauty', 'Photo & Video'],
 'Methods of teeth whitening': ['Beauty', 'Photo & Video', 'Lifestyle'],
 'Girls hairstyles 2018': ['Beauty', 'Lifestyle', 'Entertainment'],
 'Wattpad 📖 Free Books': ['Books & Reference', 'Books', 'Entertainment'],
 'E-Book Read - Read Book for free': ['Books & Reference',
  'Books',
  'Magazines & Newspapers'],
 'Download free book with green book': ['Books & Reference', 'Books'],
 'Wikipedia': ['Books & Reference', 'Reference', 'Education'],
 'Amazon Kindle': ['Books & Reference', 'Books'],
 'Cool Reader': ['Books & Reference', 'Books', 'Utilities'],
 'Dictionary - Merriam-Webster': ['Books & Reference', 'Reference', 'Books'],
 'NOOK: Read eBooks & Magazines': ['Books & Reference', 'Books', 'News'],
 'Free Panda Radio Music': ['Books & Reference', 'Music', 'Entertainment'],
 'Book store': ['Books & Reference', 'Books', 'Magazines & Newspapers'],
 'FBReader: Favorite Book Reader': ['Books & Reference', 'Books'],
 'English Grammar Complete Handbook': ['Books & Reference',
  'Education',
  'Reference'],
 'Free Books - Spirit Fanfiction and Stories': ['Books & Reference',
  'Books',
  'Magazines & Newspapers'],
 'Google Play Books': ['Books & Reference', 'Books', 'Reference'],
 'AlReader -any text book reader': ['Books & Reference',
  'Productivity',
  'Education'],
 'Offline English Dictionary': ['Books & Reference', 'Reference', 'Education'],
 'Oxford Dictionary of English : Free': ['Books & Reference',
  'Reference',
  'Education'],
 'Offline: English to Tagalog Dictionary': ['Books & Reference',
  'Reference',
  'Books'],
 'Spanish English Translator': ['Books & Reference', 'Reference', 'Travel'],
 'FamilySearch Tree': ['Books & Reference', 'Reference', 'Lifestyle'],
 'Cloud of Books': ['Books & Reference', 'Books', 'Reference'],
 'Recipes of Prophetic Medicine for free': ['Books & Reference',
  'Health & Fitness',
  'Food & Drink'],
 'ReadEra – free ebook reader': ['Books & Reference',
  'Books',
  'Magazines & Newspapers'],
 'NOOK App for NOOK Devices': ['Books & Reference',
  'Productivity',
  'Utilities'],
 'Anonymous caller detection': ['Books & Reference',
  'Utilities',
  'Productivity'],
 'Ebook Reader': ['Books & Reference', 'Books'],
 'Litnet - E-books': ['Books & Reference', 'Books', 'Magazines & Newspapers'],
 'Read books online': ['Books & Reference', 'Books', 'Entertainment'],
 'English to Urdu Dictionary': ['Books & Reference', 'Books', 'Education'],
 'eBoox: book reader fb2 epub zip': ['Books & Reference',
  'Books',
  'Productivity'],
 'English Persian Dictionary': ['Books & Reference', 'Reference', 'Education'],
 'Flybook': ['Books & Reference', 'Business'],
 'All Maths Formulas': ['Books & Reference', 'Education', 'Reference'],
 'Ancestry': ['Books & Reference', 'Reference', 'Productivity'],
 'HTC Help': ['Books & Reference', 'Utilities'],
 'English translation from Bengali': ['Books & Reference',
  'Books',
  'Education'],
 'Pdf Book Download - Read Pdf Book': ['Books & Reference',
  'Business',
  'Productivity'],
 'Free Book Reader': ['Books & Reference', 'Books', 'Magazines & Newspapers'],
 'eBoox new: Reader for fb2 epub zip books': ['Books & Reference',
  'Books',
  'Productivity'],
 'Only 30 days in English, the guideline is guaranteed': ['Books & Reference',
  'Utilities',
  'Productivity'],
 'Moon+ Reader': ['Books & Reference', 'Books', 'Utilities'],
 "SH-02J Owner's Manual (Android 8.0)": ['Books & Reference',
  'Education',
  'Reference'],
 'English-Myanmar Dictionary': ['Books & Reference', 'Reference', 'Education'],
 'Golden Dictionary (EN-AR)': ['Books & Reference', 'Reference', 'Books'],
 'All Language Translator Free': ['Books & Reference', 'Travel', 'Reference'],
 'Azpen eReader': ['Books & Reference', 'Books'],
 'URBANO V 02 instruction manual': ['Books & Reference',
  'Navigation',
  'Travel'],
 'English Dictionary - Offline': ['Books & Reference',
  'Reference',
  'Education'],
 'Visual Voicemail by MetroPCS': ['Business', 'Productivity'],
 'Indeed Job Search': ['Business', 'Utilities'],
 'Uber Driver': ['Business', 'Navigation'],
 'ADP Mobile Solutions': ['Business', 'Finance'],
 'Snag - Jobs Hiring Now': ['Business'],
 'Docs To Go™ Free Office Suite': ['Business', 'Productivity'],
 'Google My Business': ['Business', 'Productivity'],
 'OfficeSuite : Free Office + PDF Editor': ['Business', 'Productivity'],
 'USPS MOBILE®': ['Business', 'Utilities'],
 'Job Search by ZipRecruiter': ['Business', 'Lifestyle'],
 'Curriculum vitae App CV Builder Free Resume Maker': ['Business',
  'Productivity'],
 'Google Primer': ['Business', 'Productivity'],
 'Alba Heaven - Alvarez Job Portal Services': ['Business'],
 'SuperLivePro': ['Business', 'Social Networking'],
 'Facebook Pages Manager': ['Business', 'Social Networking'],
 'OfficeSuite Pro + PDF (Trial)': ['Business', 'Productivity'],
 'My Space - Employment Center': ['Business',
  'Games',
  'Role Playing',
  'Entertainment',
  'Strategy'],
 'Box': ['Business', 'Productivity'],
 'Polaris Office for LG': ['Business', 'Productivity'],
 'Call Blocker': ['Communication', 'Utilities', 'Productivity'],
 'Jobs in Alabama - Jobs in Alba': ['Business', 'Sports', 'News'],
 'Square Point of Sale - POS': ['Business', 'Finance'],
 'Plugin:AOT v5.0': ['Business', 'Utilities'],
 'Kariyer.net': ['Business', 'Utilities'],
 'SEEK Job Search': ['Business', 'Utilities'],
 'Become a Job - Find a job or advertise': ['Business', 'Utilities'],
 'ZOOM Cloud Meetings': ['Business', 'Productivity'],
 'Easy Installer - Apps On SD': ['Business', 'Utilities'],
 'Facebook Ads Manager': ['Business', 'Social Networking'],
 'IndiaMART: Search Products, Buy, Sell & Trade': ['Business', 'Shopping'],
 'ViettelPost express delivery': ['Business', 'Navigation', 'Travel'],
 'MyASUS - Service Center': ['Business', 'Productivity'],
 'Job Korea - Career Jobs': ['Business', 'Productivity'],
 '104 Looking for a job - looking for a job, looking for a job, looking for a part-time job, health checkup, resume, treatment room': ['Business'],
 'Myanmar 2D/3D': ['Business', 'Utilities'],
 'Quick PDF Scanner + OCR FREE': ['Business', 'Utilities'],
 'sABN': ['Business', 'News', 'Magazines & Newspapers'],
 'ATI Cargoes and Transportation': ['Business'],
 'Secure Folder': ['Business', 'Utilities'],
 'UPS Mobile': ['Business', 'Productivity'],
 'Y! Mobile menu': ['Business', 'Food & Drink', 'Photo & Video'],
 'SignEasy | Sign and Fill PDF and other Documents': ['Business',
  'Productivity'],
 'Genius Scan - PDF Scanner': ['Business', 'Productivity'],
 'Tiny Scanner - PDF Scanner App': ['Business', 'Productivity'],
 'Fast Scanner : Free PDF Scan': ['Business', 'Utilities'],
 'Mobile Doc Scanner (MDScan) Lite': ['Business', 'Utilities'],
 'TurboScan: scan documents and receipts in PDF': ['Business', 'Productivity'],
 'Tiny Scanner Pro: PDF Doc Scan': ['Business', 'Utilities'],
 'Zenefits': ['Business', 'Productivity'],
 'Google Ads': ['Business', 'Utilities'],
 'Slack': ['Business', 'Productivity'],
 'FreshBooks Classic': ['Business', 'Finance'],
 'Insightly CRM': ['Business', 'Productivity'],
 'QuickBooks Accounting: Invoicing & Expenses': ['Business', 'Finance'],
 'HipChat - Chat Built for Teams': ['Business', 'Productivity'],
 'Xero Accounting Software': ['Business', 'Finance'],
 'MailChimp - Email, Marketing Automation': ['Business', 'Productivity'],
 'Crew - Free Messaging and Scheduling': ['Business', 'Social Networking'],
 'Asana: organize team projects': ['Business', 'Productivity'],
 'Google Analytics': ['Business', 'Productivity'],
 'AdWords Express': ['Business', 'Utilities'],
 'Accounting App - Zoho Books': ['Business', 'Finance'],
 'Invoice & Time Tracking - Zoho': ['Business', 'Finance'],
 'join.me - Simple Meetings': ['Business', 'Productivity'],
 'Invoice 2go — Professional Invoices and Estimates': ['Business', 'Finance'],
 'Cisco Webex Meetings': ['Business', 'Productivity'],
 'ScreenMeet. Easy Phone Meeting': ['Business', 'Productivity', 'Utilities'],
 'Cisco Webex Teams': ['Business', 'Productivity'],
 'Microsoft Remote Desktop': ['Business', 'Productivity'],
 'Start Meeting': ['Business', 'Productivity'],

In [128]:
for app in playstore_data["App"]:
    if app.strip() in appstore_app_names:
        playstore_data.loc[playstore_data["App"] == app, "new_gen"] = str(play_genres_dict[app])

In [130]:
playstore_data = playstore_data.drop(["Genres"], axis = 1)
playstore_data = playstore_data.rename(columns={"new_gen" : "Genres"})

In [ ]:
#merging category names in the datasets

In [134]:
playstore_data["new_cat"] = "Yes"

In [136]:
app_cat_dict = {}
for idx, row in appstore_data.iterrows():
    app_cat_dict[row["App"]] = row["as_primary_genre"]

play_cat_dict = {}
for idx, row in playstore_data.iterrows():
    play_cat_dict[row["App"]] = ast.literal_eval(str(row["Category"]))

In [140]:
for app in appstore_app_names:
    i = app_cat_dict[app]
    if i not in play_cat_dict[app]:
        play_cat_dict[app].append(i)

In [142]:
for app in playstore_data["App"]:
    if app.strip() in appstore_app_names:
        playstore_data.loc[playstore_data["App"] == app, "new_cat"] = str(play_cat_dict[app])

In [144]:
playstore_data = playstore_data.drop(["Category"], axis = 1)
playstore_data = playstore_data.rename(columns={"new_cat" : "Category"})

In [ ]:
#cresating a min_age field

In [154]:
age_map = {
    "Everyone": 5,
    "Teen": 13,
    "Mature": 17,
    "Adults": 18,
    "Unrated": 0
}

playstore_data["Min Age"] = playstore_data["Content Rating"].map(age_map)

In [156]:
playstore_data["Content Rating"].value_counts()

Content Rating
Everyone    8714
Teen        1621
Mature       499
Adults         3
Unrated        2
Name: count, dtype: int64

In [ ]:
#Handling the reviews

In [163]:
median_reviews = appstore_data["as_reviews"].median()
print(median_reviews)

49288.0

In [171]:
playstore_data["new_rev"] = median_reviews

In [172]:
for app in playstore_data["App"]:
    old = playstore_data.loc[playstore_data["App"] == app, "Reviews"].iloc[0]
    if app in appstore_app_names:
        temp = appstore_data.loc[appstore_data["App"] == app, "as_reviews"].iloc[0]
        new = old + temp
    else:
        new = old + median_reviews
    playstore_data.loc[playstore_data["App"] == app, "new_rev"] = new

In [174]:
playstore_data = playstore_data.drop(["Reviews"], axis = 1)
playstore_data = playstore_data.rename(columns={"new_rev" : "Reviews"})

In [179]:
#Handling the Price

In [176]:
for app in playstore_data["App"]:
    old = playstore_data.loc[playstore_data["App"] == app, "Price"].iloc[0]
    if app in appstore_app_names:
        temp = appstore_data.loc[appstore_data["App"] == app, "as_price"].iloc[0]
        old = old + temp
    playstore_data.loc[playstore_data["App"] == app, "Price"] = old

In [178]:
#Handling Type

In [180]:
playstore_data["Type"].value_counts()

Type
Free    10039
Paid      800
Name: count, dtype: int64

In [185]:
for app in playstore_data["App"]:
    price = playstore_data.loc[playstore_data["App"] == app, "Price"].iloc[0]
    type = playstore_data.loc[playstore_data["App"] == app, "Type"].iloc[0]
    if price == 0:
        playstore_data.loc[playstore_data["App"] == app, "Type"] = "Free"
    else:
        playstore_data.loc[playstore_data["App"] == app, "Type"] = "Paid"

In [ ]:
#Handling score

In [191]:
playstore_data["new_rat"] = 0.0

In [192]:
for app in playstore_data["App"]:
    old = playstore_data.loc[playstore_data["App"] == app, "Rating"].iloc[0]
    if app in appstore_app_names:
        new = appstore_data.loc[appstore_data["App"] == app, "as_score"].iloc[0]
        old = (old + new) / 2
    old = round(old, 2)
    playstore_data.loc[playstore_data["App"] == app, "new_rat"] = old

In [194]:
playstore_data = playstore_data.drop(["Rating"], axis = 1)
playstore_data = playstore_data.rename(columns={"new_rat" : "Rating"})

In [15]:
#The Dataframes Head

In [187]:
appstore_data.head()

,App,as_store,as_genres,as_primary_genre,as_content_rating,as_size,as_required_os_version,as_version,as_price,as_free,as_score,as_reviews
0,Photo Editor & Candy Camera & Grid & ScrapBook,apple,"[Photo & Video, Graphics & Design]",Photo & Video,12+,224247808,15.0,5.5.7,0.0,True,4.61130,43072.0
1,Coloring book moana,apple,"[Entertainment, Education]",Entertainment,4+,1298546688,13.0,17.2.0,0.0,True,4.38417,204845.0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",apple,"[Graphics & Design, Entertainment]",Graphics & Design,4+,162102272,15.0,1.9.8,0.0,True,4.64858,30573.0
3,Sketch - Draw & Paint,apple,"[Productivity, Graphics & Design]",Productivity,4+,175809536,13.0,5.5.9,0.0,True,4.57904,68151.0
4,Pixel Draw - Number Art Coloring Book,apple,"[Entertainment, Puzzle, Family, Games]",Entertainment,4+,54242304,12.0,3.3.0,0.0,True,4.47975,4346.0

In [195]:
playstore_data.head()

,App,Installs,Type,Price,Content Rating,Last Updated,Size_MB,and_ver_min,curr_ver_min,Store,Genres,Category,Min Age,Reviews,Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,10000.0,Free,0.0,Everyone,2018-01-07,19.0,4.0,1.0,"[android, apple]","['Art & Design', 'Photo & Video', 'Graphics & ...","['ART', 'DESIGN', 'Photo & Video']",5,43231.0,4.36
1,Coloring book moana,500000.0,Free,0.0,Everyone,2018-01-15,14.0,4.0,2.0,"[android, apple]","['Art & Design', 'Pretend Play', 'Entertainmen...","['FAMILY', 'Entertainment']",5,205812.0,4.14
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",5000000.0,Free,0.0,Everyone,2018-08-01,8.7,4.0,1.2,"[android, apple]","['Art & Design', 'Graphics & Design', 'Enterta...","['ART', 'DESIGN', 'Graphics & Design']",5,118083.0,4.67
3,Sketch - Draw & Paint,50000000.0,Free,0.0,Teen,2018-06-08,25.0,4.2,2.0,"[android, apple]","['Art & Design', 'Productivity', 'Graphics & D...","['ART', 'DESIGN', 'Productivity']",13,283795.0,4.54
4,Pixel Draw - Number Art Coloring Book,100000.0,Free,0.0,Everyone,2018-06-20,2.8,4.4,1.1,"[android, apple]","['Art & Design', 'Creativity', 'Entertainment'...","['ART', 'DESIGN', 'Entertainment']",5,5313.0,4.39

In [18]:
#The Dataframes info

In [196]:
appstore_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2132 entries, 0 to 2131
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   App                     2132 non-null   object
 1   as_store                2132 non-null   object
 2   as_genres               2132 non-null   object
 3   as_primary_genre        2132 non-null   object
 4   as_content_rating       2132 non-null   object
 5   as_size                 2132 non-null   int64
 6   as_required_os_version  2132 non-null   object
 7   as_version              2132 non-null   object
 8   as_price                2132 non-null   float64
 9   as_free                 2132 non-null   bool
 10  as_score                2132 non-null   float64
 11  as_reviews              2132 non-null   float64
dtypes: bool(1), float64(3), int64(1), object(7)
memory usage: 185.4+ KB

In [197]:
playstore_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10839 entries, 0 to 10838
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10839 non-null  object
 1   Installs        10839 non-null  float64
 2   Type            10839 non-null  object
 3   Price           10839 non-null  float64
 4   Content Rating  10839 non-null  object
 5   Last Updated    10839 non-null  object
 6   Size_MB         10839 non-null  float64
 7   and_ver_min     10839 non-null  float64
 8   curr_ver_min    10839 non-null  float64
 9   Store           10839 non-null  object
 10  Genres          10839 non-null  object
 11  Category        10839 non-null  object
 12  Min Age         10839 non-null  int64
 13  Reviews         10839 non-null  float64
 14  Rating          10839 non-null  float64
dtypes: float64(7), int64(1), object(7)
memory usage: 1.2+ MB

In [198]:
print(playstore_data.isnull().sum())

App               0
Installs          0
Type              0
Price             0
Content Rating    0
Last Updated      0
Size_MB           0
and_ver_min       0
curr_ver_min      0
Store             0
Genres            0
Category          0
Min Age           0
Reviews           0
Rating            0
dtype: int64

In [199]:
print(playstore_data.isna().mean() * 100)

App               0.0
Installs          0.0
Type              0.0
Price             0.0
Content Rating    0.0
Last Updated      0.0
Size_MB           0.0
and_ver_min       0.0
curr_ver_min      0.0
Store             0.0
Genres            0.0
Category          0.0
Min Age           0.0
Reviews           0.0
Rating            0.0
dtype: float64

In [200]:
#Saving the merged datset

In [208]:
playstore_data = playstore_data.rename(columns={"Size_MB" : "Size", "and_ver_min" : "OS Version", "curr_ver_min" : "Version"})

In [209]:
playstore_data.to_csv("dataset/updated_cleaned_combined.csv", index=False)
print("Cleaned dataset saved")

Cleaned dataset saved

In [210]:
df = pd.read_csv("dataset/updated_cleaned_combined.csv")

In [211]:
df.head()

,App,Installs,Type,Price,Content Rating,Last Updated,Size,OS Version,Version,Store,Genres,Category,Min Age,Reviews,Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,10000.0,Free,0.0,Everyone,2018-01-07,19.0,4.0,1.0,"[android, apple]","['Art & Design', 'Photo & Video', 'Graphics & ...","['ART', 'DESIGN', 'Photo & Video']",5,43231.0,4.36
1,Coloring book moana,500000.0,Free,0.0,Everyone,2018-01-15,14.0,4.0,2.0,"[android, apple]","['Art & Design', 'Pretend Play', 'Entertainmen...","['FAMILY', 'Entertainment']",5,205812.0,4.14
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",5000000.0,Free,0.0,Everyone,2018-08-01,8.7,4.0,1.2,"[android, apple]","['Art & Design', 'Graphics & Design', 'Enterta...","['ART', 'DESIGN', 'Graphics & Design']",5,118083.0,4.67
3,Sketch - Draw & Paint,50000000.0,Free,0.0,Teen,2018-06-08,25.0,4.2,2.0,"[android, apple]","['Art & Design', 'Productivity', 'Graphics & D...","['ART', 'DESIGN', 'Productivity']",13,283795.0,4.54
4,Pixel Draw - Number Art Coloring Book,100000.0,Free,0.0,Everyone,2018-06-20,2.8,4.4,1.1,"[android, apple]","['Art & Design', 'Creativity', 'Entertainment'...","['ART', 'DESIGN', 'Entertainment']",5,5313.0,4.39

In [212]:
df.tail()

,App,Installs,Type,Price,Content Rating,Last Updated,Size,OS Version,Version,Store,Genres,Category,Min Age,Reviews,Rating
10834,Sya9a Maroc - FR,5000.0,Free,0.0,Everyone,2017-07-25,53.0,4.1,1.48,[android],Yes,Yes,5,49326.0,4.5
10835,Fr. Mike Schmitz Audio Teachings,100.0,Free,0.0,Everyone,2018-07-06,3.6,4.1,1.00,[android],Yes,Yes,5,49292.0,5.0
10836,Parkinson Exercices FR,1000.0,Free,0.0,Everyone,2017-01-20,9.5,2.2,1.00,[android],Yes,Yes,5,49291.0,4.3
10837,The SCP Foundation DB fr nn5n,1000.0,Free,0.0,Mature,2015-01-19,13.0,4.1,2.00,[android],Yes,Yes,17,49402.0,4.5
10838,iHoroscope - 2018 Daily Horoscope & Astrology,10000000.0,Free,0.0,Everyone,2018-07-25,19.0,4.1,2.00,[android],Yes,Yes,5,447595.0,4.5

In [213]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10839 entries, 0 to 10838
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10839 non-null  object
 1   Installs        10839 non-null  float64
 2   Type            10839 non-null  object
 3   Price           10839 non-null  float64
 4   Content Rating  10839 non-null  object
 5   Last Updated    10839 non-null  object
 6   Size            10839 non-null  float64
 7   OS Version      10839 non-null  float64
 8   Version         10839 non-null  float64
 9   Store           10839 non-null  object
 10  Genres          10839 non-null  object
 11  Category        10839 non-null  object
 12  Min Age         10839 non-null  int64
 13  Reviews         10839 non-null  float64
 14  Rating          10839 non-null  float64
dtypes: float64(7), int64(1), object(7)
memory usage: 1.2+ MB

In [214]:
df.describe()

,Installs,Price,Size,OS Version,Version,Min Age,Reviews,Rating
count,1.083900e+04,10839.000000,10839.000000,10839.000000,1.083900e+04,10839.000000,1.083900e+04,10839.000000
mean,1.546577e+07,0.208264,20.185195,3.895821,1.414680e+05,6.751545,6.894724e+05,4.238834
std,8.503315e+07,4.398729,20.977970,0.787189,1.207675e+07,3.631178,3.780706e+06,0.489195
min,0.000000e+00,0.000000,0.008301,1.000000,0.000000e+00,0.000000,0.000000e+00,1.000000
25%,3.000000e+03,0.000000,5.900000,4.000000,1.180000e+00,5.000000,4.930000e+04,4.100000
50%,1.000000e+05,0.000000,13.000000,4.100000,2.000000e+00,5.000000,5.081900e+04,4.300000
75%,5.000000e+06,0.000000,26.000000,4.100000,3.150000e+00,5.000000,1.551395e+05,4.510000
max,1.000000e+09,249.990000,100.000000,8.000000,1.255162e+09,18.000000,1.007101e+08,5.000000

In [215]:
df["Last Updated"].value_counts()

Last Updated
2018-08-03    326
2018-08-02    304
2018-07-31    294
2018-08-01    285
2018-07-30    211
             ...
2015-03-08      1
2015-03-25      1
2013-12-17      1
2014-10-11      1
2014-03-23      1
Name: count, Length: 1377, dtype: int64